DCM.VGDB.MVC/Controllers/SystemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DCM.VGDB.MVC.Controllers
{
    public class SystemsController : Controller
    {
        DCM.VGDB.BLL.Provider.SystemProvider p = new BLL.Provider.SystemProvider();

        // GET: Console
        public ActionResult Index(string id)
        {
            return View(p.GetByTitle(id));
        }

        // GET: Console/Details/5
        public ActionResult Details(string system_name)
        {
            return View();
        }

        public ActionResult NavigationList()
        {
            return PartialView("_SystemNavigation", p.GetList());
        }

        // GET: Console/Create
        [Authorize(Roles="Administrators")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Console/Create
        [HttpPost]
        [Authorize(Roles = "Administrators")]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Console/Edit/5
        [Authorize(Roles = "Administrators")]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Console/Edit/5
        [HttpPost]
        [Authorize(Roles = "Administrators")]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Console/Delete/5
        [Authorize(Roles = "Administrators")]
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Console/Delete/5
        [HttpPost]
        [Authorize(Roles = "Administrators")]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

DCM.VGDB.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Video Game Database</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="col-lg-3">
            @{Html.RenderAction("NavigationList", "Systems");}
        </div>
        <div class="col-lg-9">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Denver Code Monkey - Video Game Database</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DCM.VGDB.MVC/Views/Shared/_SystemNavigation.cshtml
@model IEnumerable<DCM.VGDB.DTO.SystemDTO>

<ul>
    @foreach (var item in Model)
    {
        <li>
            @Html.ActionLink(item.Title, "Index", "Systems", new { id = item.Title }, null)
        </li>
    }
</ul>